version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/base:stable

orbs:
  node: circleci/node@4.1.0

jobs:

  build:
    executor: node-executor
    steps:
      # Checkout Project
      - checkout

      - run: node --version

      # Setup yarn PackageManager
      - node/install-packages:
          install-yarn: true

      - run: yarn install & npm run package-install
      - run: yarn run lint
      - run: yarn run build

      # https://circleci.com/docs/2.0/configuration-reference/#persist_to_workspace
      - persist_to_workspace:
          root: .
          paths: [ ./* ]

  test:
    executor: node-executor
    steps:
      # https://circleci.com/docs/2.0/configuration-reference/#attach_workspace
      - attach_workspace:
          at: .

      - run: yarn run test

  test-coverage:
    executor: node-executor
    steps:
      # https://circleci.com/docs/2.0/configuration-reference/#attach_workspace
      - attach_workspace:
          at: .

      - run: yarn run test:coverage

      # https://circleci.com/docs/2.0/configuration-reference/#store_test_results
      - store_test_results:
          path: ./test-results

      # https://circleci.com/docs/2.0/configuration-reference/#persist_to_workspace
      - persist_to_workspace:
          root: .
          paths: [./*]

workflows:
  build-and-test:
    jobs:

      # Run Build Job
      - build

      # Run Test Job if Build Job has finished
      - test:
          requires:
            - build

      # Run Test-Coverage Job if Build Job has finished
      - test-coverage:
          requires:
            - build
